# Generated by Django 3.1.7 on 2021-03-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210319_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('categoria1', 'categoria1'), ('categoria2', 'categoria2')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('por salir', 'por salir'), ('enviado', 'enviado')], max_length=255, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cliente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.producto')),
            ],
        ),
    ]
