# Generated by Django 3.1.7 on 2021-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210319_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='tags',
            field=models.ManyToManyField(to='usuarios.Tag'),
        ),
    ]
