# Generated by Django 3.1.7 on 2021-03-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210319_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nota',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tags',
            field=models.ManyToManyField(null=True, to='usuarios.Tag'),
        ),
    ]
